### ISSUE TITLE
Gradle: Update to version 5.2

### ISSUE THREAD

**Issue by czirkelbach** [ExplorViz/explorviz-backend-shared#1]
For the next release we should update our multiprojects and update them to be based on Gradle version 5.2. Related to https://github.com/ExplorViz/explorviz-backend/issues/49.

**Comment by Alexander-Krause-Glau** [comment]
Shared project is already [5.2.1](https://github.com/ExplorViz/explorviz-backend-shared/blob/master/gradle/wrapper/gradle-wrapper.properties).

Close?
